# 1. ndarray数据类型


### ndarray的多维性

In [7]:
import numpy as np

In [10]:
arr = np.array(5) # 创建0维数组
print(arr)
print('arr的维度为:',arr.ndim)

5
arr的维度为: 0


In [16]:
arr = np.array([[1,2,3],[4,5,6]])  # 创建2维数组
print(arr)
print('arr的维度为:',arr.ndim)

[[1 2 3]
 [4 5 6]]
arr的维度为: 2


### ndarray的同质性
- 不同的数据类型会被强制转换为相同的数据类型

In [17]:
arr = np.array([1,'hello']) # 不同的数据类型会被强制转换为相同的数据类型
print(arr)

['1' 'hello']


In [18]:
arr = np.array([1,2.5]) # 不同的数据类型会被强制转换为相同的数据类型
print(arr)

[1.  2.5]


# 2. ndarray的属性
1. ndarray.ndim: 获取数组的维度
2. ndarray.shape: 获取数组的形状
3. ndarray.size: 获取数组的元素个数
4. ndarray.dtype: 获取数组的数据类型
5. ndarray.T: 获取数组的转置


In [28]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)
print('arr的维度为:',arr.ndim)
print('arr的形状为:',arr.shape)
print('arr的元素个数为:',arr.size)
print('arr的数据类型为:',arr.dtype)
print('arr数组转置为:',arr.T)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
arr的维度为: 2
arr的形状为: (3, 3)
arr的元素个数为: 9
arr的数据类型为: int64
arr数组转置为: [[1 4 7]
 [2 5 8]
 [3 6 9]]


### 2.1 ndarray的创建方式
1. 基础构造: 适用于手动构建小规模数组或复制已有数据。
2. 预定义形状填充: 用于快速初始化固定形状的数组(如全0占位、全1初始化)。
3. 基于数值范围生成: 生成数值序列,常用于模拟时间序列、坐标网格等。
4. 特殊矩阵生成: 数学运算专用(如线性代数中的单位矩阵)。
5. 随机数组生成: 模拟实验数据、初始化神经网络权重等场景。
6. 高级构造方法: 处理非结构化数据(如文件、字符串)或通过函数生成复杂数组。