# 1. ndarray数据类型


### ndarray的多维性

In [7]:
import numpy as np

In [10]:
arr = np.array(5)  # 创建0维数组
print(arr)
print('arr的维度为:', arr.ndim)

5
arr的维度为: 0


In [16]:
arr = np.array([[1, 2, 3], [4, 5, 6]])  # 创建2维数组
print(arr)
print('arr的维度为:', arr.ndim)

[[1 2 3]
 [4 5 6]]
arr的维度为: 2


### ndarray的同质性
- 不同的数据类型会被强制转换为相同的数据类型

In [17]:
arr = np.array([1, 'hello'])  # 不同的数据类型会被强制转换为相同的数据类型
print(arr)

['1' 'hello']


In [18]:
arr = np.array([1, 2.5])  # 不同的数据类型会被强制转换为相同的数据类型
print(arr)

[1.  2.5]


# 2. ndarray的属性
1. ndarray.ndim: 获取数组的维度
2. ndarray.shape: 获取数组的形状
3. ndarray.size: 获取数组的元素个数
4. ndarray.dtype: 获取数组的数据类型
5. ndarray.T: 获取数组的转置


In [242]:
arr = np.array([
    [[255, 0, 0], [0, 255, 0], [0, 0, 255], [255, 255, 0], [0, 255, 255]],
    [[100, 100, 100], [200, 50, 50], [50, 200, 50], [50, 50, 200], [255, 0, 0]],
    [[0, 0, 0], [255, 255, 255], [128, 128, 128], [0, 0, 0], [100, 100, 100]],
    [[255, 0, 255], [0, 255, 255], [255, 255, 0], [0, 0, 0], [255, 255, 255]]
])
print('arr的维度为:', arr.ndim)
print('arr的形状为:', arr.shape)
print('arr的元素个数为:', arr.size)
print('arr的数据类型为:', arr.dtype)
print('arr数组转置为:', arr.T)

arr的维度为: 3
arr的形状为: (4, 5, 3)
arr的元素个数为: 60
arr的数据类型为: int64
arr数组转置为: [[[255 100   0 255]
  [  0 200 255   0]
  [  0  50 128 255]
  [255  50   0   0]
  [  0 255 100 255]]

 [[  0 100   0   0]
  [255  50 255 255]
  [  0 200 128 255]
  [255  50   0   0]
  [255   0 100 255]]

 [[  0 100   0 255]
  [  0  50 255 255]
  [255  50 128   0]
  [  0 200   0   0]
  [255   0 100 255]]]


### 2.1 ndarray的创建方式
1. 基础构造: 适用于手动构建小规模数组或复制已有数据。
2. 预定义形状填充: 用于快速初始化固定形状的数组(如全0占位、全1初始化)。
3. 基于数值范围生成: 生成数值序列,常用于模拟时间序列、坐标网格等。
4. 特殊矩阵生成: 数学运算专用(如线性代数中的单位矩阵)。
5. 随机数组生成: 模拟实验数据、初始化神经网络权重等场景。
6. 高级构造方法: 处理非结构化数据(如文件、字符串)或通过函数生成复杂数组。

# 3. ndarray数组的创建

### 3.1 基础的创建方法

In [42]:
arr = np.array([1, 2, 3], dtype=np.float64)
print(arr)

[1. 2. 3.]


In [44]:
# Copy函数
arr1 = np.copy(arr)
print(arr1)

# 注意arr1元素和初始的相同，但已经不是同一个数组了
arr1[1] = 8
print('修改后新数组的值', arr1)
print('旧数组的值', arr)

[1. 2. 3.]
修改后新数组的值 [1. 8. 3.]
旧数组的值 [1. 2. 3.]


### 3.2 预定义形状（全0，全1，未初始化，固定值）

In [60]:
# 创建全0数组
arr = np.zeros((2, 3))
print(arr)

# 创建全1数组
arr = np.ones((10,))
print(arr)

# 创建未初始化类型,随机数据填充
arr = np.empty((4, 5))
print(arr)

# 创建固定值
arr = np.full((3, 5), 2026)
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[4.21207831e-315 0.00000000e+000 2.12199585e-314 0.00000000e+000
  1.17637030e-320]
 [2.97079411e-313 0.00000000e+000 1.17637030e-320 2.12199585e-314
  0.00000000e+000]
 [1.17637030e-320 3.18299369e-313 0.00000000e+000 1.17637030e-320
  2.12199585e-314]
 [0.00000000e+000 1.17686437e-320 3.39519327e-313 0.00000000e+000
  1.17686437e-320]]
[[2026 2026 2026 2026 2026]
 [2026 2026 2026 2026 2026]
 [2026 2026 2026 2026 2026]]


In [83]:
arr1 = np.zeros_like(arr)
print('zero_like函数模仿形状，用0填充\n', arr1)
arr1 = np.ones_like(arr)
print('ones_like函数模仿形状，用1填充\n', arr1)
arr1 = np.empty_like(arr)
print('empty_like函数模仿形状，用空值填充\n', arr1)
arr1 = np.full_like(arr, 2026)
print('full_like函数模仿形状，用固定值填充\n', arr1)

zero_like函数模仿形状，用0填充
 [[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
ones_like函数模仿形状，用1填充
 [[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
empty_like函数模仿形状，用空值填充
 [[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
full_like函数模仿形状，用固定值填充
 [[2026 2026 2026 2026 2026]
 [2026 2026 2026 2026 2026]
 [2026 2026 2026 2026 2026]]


### 3.3 数值范围生成

In [88]:
# 等差数列生成,参数开始，截至，步长
arr = np.arange(1, 10, 1)
print(arr)

[1 2 3 4 5 6 7 8 9]


In [91]:
# 等间隔数列,用于划分间隔，参数开始，截至，分的份数
arr = np.linspace(0, 100, 5)
print(arr)

[  0.  25.  50.  75. 100.]


In [95]:
# 对数间隔序列,默认base是10
arr = np.logspace(0, 4, 3, base=3)
print(arr)

[ 1.  9. 81.]


### 3.4 特殊矩阵的生成
- 标量：0维
- 向量：1维
- 矩阵：2维
- 张量：3维及以上

In [100]:
# 构造单位矩阵
arr = np.eye(3, 3, dtype=int)
print(arr)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [101]:
# 构造对角矩阵
arr = np.diag([1, 2, 3, 4])
print(arr)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [124]:
# 随机数组的生成

# 生成0到1之间的随机浮点数（均匀分布）
arr = np.random.rand(2, 3)
print(arr)
# 生成指定范围的随机浮点数
arr = np.random.uniform(3, 6, (2, 3))
print(arr)
# 生成指定范围的区间的随机整数
arr = np.random.randint(1, 10, (2, 3))
print(arr)

[[0.24353328 0.41840548 0.3055792 ]
 [0.04058362 0.52418013 0.38566643]]
[[5.04347049 3.18763875 3.22610648]
 [3.28819015 5.96696852 3.25222955]]
[[6 3 5]
 [5 8 3]]


In [126]:
# 生成标准正态分布的随机数(大部分是-3到3之间的数字)
arr = np.random.randn(2, 3)
print(arr)

[[ 0.70019041  0.96144978 -1.2347799 ]
 [ 0.28009403  0.48952114  0.35778986]]


In [163]:
# 设置随机种子seed(保证复现以及多次生成的时候，数据保持不变)
np.random.seed(20)
arr = np.random.randint(1, 10, (2, 5))
print(arr)


[[4 5 7 8 3]
 [1 7 9 6 4]]


# 4. ndarray的数据类型

| 数据类型       | 说明                              |
|----------------|-----------------------------------|
| bool           | 布尔类型                          |
| int8, uint8    | 有符号、无符号的8位(1字节)整型     |
| int16, uint16  | 有符号、无符号的16位(2字节)整型    |
| int32, uint32  | 有符号、无符号的32位(4字节)整型    |
| int64, uint64  | 有符号、无符号的64位(8字节)整型    |
| float16        | 半精度浮点型                      |
| float32        | 单精度浮点型                      |
| float64        | 双精度浮点型                      |
| complex64      | 用两个32位浮点数表示的复数         |
| complex128     | 用两个64位浮点数表示的复数         |

In [168]:
arr = np.array([1, 127], dtype=np.int8)
print(arr)

[  1 127]


# 5. ndarray索引与切片
| 索引/切片类型     | 描述/用法                                |
|-------------|--------------------------------------|
| 基本索引        | 通过整数索引直接访问元素。索引从0开始。                 |
| 行/列切片       | 使用冒号 `:` 切片语法选择行或列的子集。               |
| 连续切片        | 从起始索引到结束索引按步长切片。                     |
| 使用 slice 函数 | 通过 `slice(start, stop, step)` 定义切片规则。 |
| 布尔Bool索引    | 通过布尔条件筛选满足条件的元素。支持逻辑运算符 `&`、`\|`         |

In [185]:
# 1维数组的索引与切片
arr = np.random.randint(1, 100, 20)
print(arr)

print(arr[0])
print(arr[:])  # 冒号获取全部的数据
print(arr[2:5])  # 获取部分数据，start到end+1(左边包括，右边不包括)
print(arr[slice(2, 75, 3)])  # slice参数 start,end,step
print(arr[(arr > 20) & (arr < 70)])  # 布尔索引，注意可以使用and & 和 or |


[30 76 84 17 55 54 74 83 67 31 55 66 45 96 44 59 36 41 22  1]
30
[30 76 84 17 55 54 74 83 67 31 55 66 45 96 44 59 36 41 22  1]
[84 17 55]
[84 54 67 66 44 41]
[30 55 54 67 31 55 66 45 44 59 36 41 22]


In [196]:
# 2维数组的索引与切片
arr = np.random.randint(1, 100, [4, 8])
print(arr)

print(arr[2, 4])  # 固定位置取数
print(arr[1, 2:5])  # 冒号获取某一行的数据,获取部分数据，start到end+1(左边包括，右边不包括)
print('行数据使用bool索引寻找\n', arr[2][arr[2] > 50])  # 布尔索引，某一行大于50的数据
print('列数据使用bool索引寻找\n', arr[:, 3][arr[:, 3] > 50])  # 布尔索引，某一列大于50的数据

[[76 71 50 61 80 77 30 52]
 [ 9 68 89 66 96 49 82  1]
 [32 62 95 48 44 61 43 78]
 [61 82 72 98 28 18 17 86]]
44
[89 66 96]
行数据使用bool索引寻找
 [62 95 61 78]
列数据使用bool索引寻找
 [61 66 98]


# 6. ndarray的运算

In [200]:
# 基础的算数运算
# 一维数组加减乘除运算
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(a ** 2)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[1 4 9]


#### Notes：注意这里不是矩阵运算
`+ - * / **` 只是逐元素运算,不是矩阵运算

In [202]:
# 二维数组的运算
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])
print(A + B)
print(A - B)
print(A * B)  # Hadamard product,逐元素相乘不是矩阵乘法
print(A / B)

[[10 10 10]
 [10 10 10]
 [10 10 10]]
[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]
[[ 9 16 21]
 [24 25 24]
 [21 16  9]]
[[0.11111111 0.25       0.42857143]
 [0.66666667 1.         1.5       ]
 [2.33333333 4.         9.        ]]


In [221]:
# 数组与标量运算
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(A + 3)
print(A * 3)


[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 3  6  9]
 [12 15 18]
 [21 24 27]]


#### Broadcast广播机制
1. 数组在形状上不一致，变成一致的以后进行运算
2. 运算规则
```plaintext
    从右边开始看每一对维度：

    相等 → 继续
    其中一个是 1 → 可以（1会被拉伸）
    都不相等，也都不是 1 → 报错

    最终形状 = 每一维度取 较大的那个数
```

In [222]:
# 广播机制
'''
    同一维度相同，或者有一个为1
'''
a = np.array([1, 2, 3])  #1*3
b = np.array([[4], [5], [6]])  #3*1
'''
    同一维度相同，或者有一个为1
    a
    1 2 3
    1 2 3
    1 2 3
    b
    4 4 4
    5 5 5
    6 6 6
'''
print(a + b)

[[5 6 7]
 [6 7 8]
 [7 8 9]]


In [247]:
# 不能广播
a = np.zeros((6, 4))
print(a.shape)
b = np.ones((4, 1))
print(b.shape)
print(b - a)

(6, 4)
(4, 1)


ValueError: operands could not be broadcast together with shapes (4,1) (6,4) 

#### 在矩阵中的运算规则
- 矩阵乘法
- 矩阵乘向量
- 转置(上面 ndarray的属性)
- 每个元素加/乘标量(上面 自动广播)

In [236]:
# 矩阵乘法
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])

print(A @ B)

# 矩阵 * 向量
v = np.array([10, 20])
print(A @ v)

[[19 22]
 [43 50]]
[ 50 110]
