# Numpy实战练习

题目 1:温度数据分析
某城市一周的最高气温(℃)为 [28, 30, 29, 31, 32, 30,29]。
 - 计算平均气温、最高气温和最低气温。
 - 找出气温超过30℃的天数。

In [10]:
import numpy as np
from numpy.conftest import dtype

temps = np.array([28, 30, 29, 31, 32, 30, 29])
print(temps)
print('平均气温%.3f' % np.mean(temps))
print('最高气温', np.max(temps))
print('最低气温', np.min(temps))
print('超过30度的天数', len(temps[temps > 30]))

[28 30 29 31 32 30 29]
平均气温29.857
最高气温 32
最低气温 28
超过30度的天数 2
超过30度的天数 1


题目 2:学生成绩统计
某班级 5 名学生的数学成绩为 [85, 90, 78,92,88]。
- 计算成绩的平均分、中位数和标准差。
- 将成绩转换为十分制。

In [18]:
score = np.array([85, 90, 78, 92, 88])
print('成绩的平均分：', np.mean(score))
print('成绩的中位数', np.median(score))
print('成绩的标准差', np.std(score))

# 转换为10分制
print(score / 10)

成绩的平均分： 86.6
成绩的中位数 88.0
成绩的标准差 4.882622246293481
[8.5 9.  7.8 9.2 8.8]


题目 3:矩阵运算
给定矩阵 A = [[1, 2], [3, 4]] 和B = [[5, 6], [7, 8]]。
- 计算 A + B和AB(逐元素乘法)。
- 计算A和B的矩阵乘法(点积)。

In [19]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print('A+B的值为：\n', A + B)
print('A*B的值为：\n', A * B)
print('A和B的矩阵乘法\n', A @ B)

A+B的值为：
 [[ 6  8]
 [10 12]]
A*B的值为：
 [[ 5 12]
 [21 32]]
A和B的矩阵乘法
 [[19 22]
 [43 50]]


题目 4:随机数据生成
生成一个(3,4)的随机整数数组,范围[0,10)
- 计算每列的最大值和每行的最小值。
- 将数组中的所有奇数替换为-1。

In [33]:
np.random.seed(42)
temps = np.random.randint(0, 10, (3, 4))
print('生成的数组为\n', temps)

print('计算每一列的最大值', np.max(temps, axis=0))  # axis=0代表的是列，axis=1代表的是行
print('计算每行的最小值', np.min(temps, axis=1))

#print('所有的奇数替换为-1后的结果\n', np.where(temps % 2 == 1, -1, temps))
for i in range(temps.shape[0]):
    for j in range(temps.shape[1]):
        if temps[i][j] % 2 == 1:
            temps[i][j] = -1
print('所有的奇数替换为-1后的结果\n', temps)

生成的数组为
 [[6 3 7 4]
 [6 9 2 6]
 [7 4 3 7]]
计算每一列的最大值 [7 9 7 7]
计算每行的最小值 [3 2 3]
所有的奇数替换为-1后的结果
 [[ 6 -1 -1  4]
 [ 6 -1  2  6]
 [-1  4 -1 -1]]


题目 5:数组变形
创建一个1到12的一维数组,并转换为(3,4)的二维数组。
- 计算每行的和与每列的平均值。
- 将数组展平为一维数组。

In [48]:
arr = np.arange(1, 13)
print('创建好的一维数组为\n', arr)
arr = np.reshape(arr, (3, 4))
print('转换为2维数组后\n', arr)
print('每行的和为\n', np.sum(arr, axis=1))
print('每列的平均值\n', np.mean(arr, axis=0))

arr = np.reshape(arr, (12))
print(arr)

创建好的一维数组为
 [ 1  2  3  4  5  6  7  8  9 10 11 12]
转换为2维数组后
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
每行的和为
 [10 26 42]
每列的平均值
 [5. 6. 7. 8.]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


生成一个(5,5)的随机数组,范围[0,20)。
- 找出数组中大于10的元素。
- 将所有大于10 的元素替换为0。

In [55]:
np.random.seed(42)
arr = np.random.randint(0, 20, (5, 5))
print('生成的随机数组为\n', arr)
print('大于10的元素', arr[arr > 10])
print('大于10的元素替换为0\n', np.where((arr > 10), 0, arr))

生成的随机数组为
 [[ 6 19 14 10  7]
 [ 6 18 10 10  3]
 [ 7  2  1 11  5]
 [ 1  0 11 11 16]
 [ 9 15 14 14 18]]
大于10的元素 [19 14 18 11 11 11 16 15 14 14 18]
大于10的元素替换为0
 [[ 6  0  0 10  7]
 [ 6  0 10 10  3]
 [ 7  2  1  0  5]
 [ 1  0  0  0  0]
 [ 9  0  0  0  0]]


题目 7:统计函数应用
某公司 6个月的销售额(万元)为 [120, 135, 110, 125, 130, 140]。
- 计算销售额的总和、均值和方差。
- 找出销售额最高的月份和最低的月份。

In [59]:
sale = np.array([120, 135, 110, 125, 130, 140])
print('六个月的销售额为:', sale)
print('销售额的总和为：', np.sum(sale))
print('销售额的均值为：', np.mean(sale))
print('销售额的方差为：', np.var(sale))

print('销售额最高的月份：', np.argmax(sale) + 1)
print('销售额最低的月份：', np.argmin(sale) + 1)

六个月的销售额为: [120 135 110 125 130 140]
销售额的总和为： 760
销售额的均值为： 126.66666666666667
销售额的方差为： 97.22222222222223
销售额最高的月份： 6
销售额最低的月份： 3


题目 8:数组拼接
给定 A = [1, 2, 3] 和B = [4, 5, 6]。
- 将A和B水平拼接为一个新数组。
- 将A和B垂直拼接为一个新数组。

In [65]:
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])
C = np.concatenate((A, B))
print('水平拼接A和B', C)
print('垂直拼接A和B\n', np.vstack((A, B)))

水平拼接A和B [1 2 3 4 5 6]
垂直拼接A和B
 [[1 2 3]
 [4 5 6]]
