In [1]:
import numpy as np
import torch

### 1. 按内容创建张量
- 传入什么内容，输出格式就是什么类型

In [5]:
tensor1 = torch.tensor(10.0)
print(tensor1)
print(tensor1.size())
print(tensor1.dtype)


tensor(10.)
torch.Size([])
torch.float32


In [9]:
# 传入一个一维数组
tensor2 = torch.tensor([1.0, 2, 3])
print(tensor2)
print(tensor2.size())
print(tensor2.dtype)

# 传入一个二维数组
tensor3 = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(tensor3)
print(tensor3.size())
print(tensor3.dtype)


tensor([1., 2., 3.])
torch.Size([3])
torch.float32
tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 3])
torch.int64


### 2. 创建指定形状的张量
- 大写的**Tensor**,传入形状
- 大写的**Tensor**,传入数据

注意不论是哪一种写法最后的数据格式都是float32

In [10]:
# 底层元素是一个2*4的矩阵，然后有三个这样的矩阵
tensor1 = torch.Tensor(3, 2, 4)
print(tensor1)
print(tensor1.size())
# 创建出来的张量默认float32
print(tensor1.dtype)

tensor([[[1.3985e-33, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]],

        [[0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]],

        [[0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]]])
torch.Size([3, 2, 4])
torch.float32


In [11]:
tensor2 = torch.Tensor([[1, 2, 3, 4], [4, 5, 6, 7]])
print(tensor2)
print(tensor2.size())
print(tensor2.dtype)

tensor([[1., 2., 3., 4.],
        [4., 5., 6., 7.]])
torch.Size([2, 4])
torch.float32


### 3. 按照类型创建张量

In [13]:
# 创建整数类型
# LongIntTensor-int64; ShortIntTensor-int16; ByteIntTensor-int8
tensor1 = torch.IntTensor(2, 3)
tensor2 = torch.tensor([1, 2, 3], dtype=torch.int64)
print(tensor1.dtype)
print(tensor2.dtype)

torch.int32
torch.int64


In [15]:
# 创建浮点类型
# 单精度float; 双精度 double; 半精度 half
tensor1 = torch.DoubleTensor(2, 3)
tensor2 = torch.tensor([1, 2, 3], dtype=torch.float64)
print(tensor1.dtype)
print(tensor2.dtype)

torch.float64
torch.float64


In [16]:
# 创建布尔类型
tensor1 = torch.BoolTensor(2, 3)
tensor2 = torch.tensor([1, 2, 3], dtype=torch.bool)
print(tensor1.dtype)
print(tensor2.dtype)

torch.bool
torch.bool
