# Numpy中常用的函数

In [2]:
import numpy as np

### 1. 基本的数学函数

In [14]:
# 计算平方根
arr = np.array([4, 9, 16, 25])
print(np.sqrt(arr))

[2. 3. 4. 5.]


In [15]:
# 计算指数,默认以e为底
arr = np.array([1, 2, 3])
print(np.exp(arr))

[ 2.71828183  7.3890561  20.08553692]


In [16]:
# 计算对数
arr = np.array([1, 10, 100, 1000])
print(np.log(arr))  # log是以e为底
print(np.log10(arr))
print(np.log2(arr))

[0.         2.30258509 4.60517019 6.90775528]
[0. 1. 2. 3.]
[0.         3.32192809 6.64385619 9.96578428]


In [17]:
# 计算三角函数
arr = np.array([0, np.pi / 2, np.pi])
print(np.sin(arr))
print(np.cos(arr))
print(np.tan(arr))

[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [3]:
# 计算统计量
arr = np.array([1, 2, 3, 4, 5])
print(np.abs(arr))
print(np.sum(arr))
print(np.mean(arr))
print(np.median(arr))  # 偶数两个数之间的平均值，技术排序后中间的值
print(np.std(arr))
print(np.var(arr))
print(np.min(arr))
print(np.max(arr))
print(np.argmin(arr))  # 注意是数组的下标与实际的差距记得+1
print(np.argmax(arr))

[1 2 3 4 5]
15
3.0
3.0
1.4142135623730951
2.0
1
5
0
4


### 2. 比较函数

In [32]:
# 是否大于、小于、等于
print(np.greater(arr, 3))
print(np.less(arr, 3))
print(np.equal(arr, 3))
# 逻辑与或非
print(np.logical_and([0, 0], [1, 1]))
print(np.logical_or([0, 0], [1, 1]))
print(np.logical_not([0, 0]))
# 检查数组是否有一个为True，是否所有的都为True，自定义条件
print(np.any([0, 0, 0, 0, 0]))
print(np.all([1, 1, 1, 1, 1]))
print(np.where(arr > 3, '及格', '不及格'))  # 条件 满足条件 不满足条件


[False False False  True  True]
[ True  True False False False]
[False False  True False False]
[False False]
[ True  True]
[ True  True]
False
True
['不及格' '不及格' '不及格' '及格' '及格']


### 3.排序函数

In [46]:
# 排序函数
np.random.seed(42)
arr = np.random.randint(1, 100, 20)
print(arr)
arr.sort()
print(np.argsort(arr))  # 排序后显示索引
print(arr)

[52 93 15 72 61 21 83 87 75 75 88 24  3 22 53  2 88 30 38  2]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 2  2  3 15 21 22 24 30 38 52 53 61 72 75 75 83 87 88 88 93]


In [50]:
# 去重函数(去重的同时也会排序)
print(np.unique(arr))

[ 2  3 15 21 22 24 30 38 52 53 61 72 75 83 87 88 93]


In [52]:
# 数组的拼接
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print(np.concatenate((arr1, arr2)))  # 拼接

[1 2 3 4 5 6]


In [53]:
# 数组的切割
print(np.split(arr, 5))

[array([ 2,  2,  3, 15]), array([21, 22, 24, 30]), array([38, 52, 53, 61]), array([72, 75, 75, 83]), array([87, 88, 88, 93])]


In [55]:
# 调整数组的形状
print(np.reshape(arr, [4, 5]))

[[ 2  2  3 15 21]
 [22 24 30 38 52]
 [53 61 72 75 75]
 [83 87 88 88 93]]
